vich_uploader:
    db_driver: orm

    mappings:
        logos_comercios:
            uri_prefix: '%app.path.logos_comercios%'
            upload_destination: '%kernel.project_dir%/public%app.path.logos_comercios%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
