easy_admin:
    entities:
        Comercio:
            class: App\Entity\Comercio
            list:
                fields: ['nombre', 'direccion', { property: 'nombreLogo', type: 'image', base_path: '%app.path.logos_comercios%' }, 'activo']
            form:
                form_options: { validation_groups: [false] }
                fields:
                  - { property: 'nombre' }
                  - { property: 'direccion' }
                  - { property: 'linkGoogleMaps' }
                  - { property: 'archivoLogo', type: 'vich_file', type_options: { required: false } }
                  - { property: 'observacion', type: 'fos_ckeditor' }
                  - { property: 'rubro' }
                  - { property: 'activo', type_options: { required: false } }