easy_admin:
    entities:
        Rubro:
            class: App\Entity\Rubro
            form:
                fields:
                  - { property: 'nombre' }
                  - { property: 'activo' }