easy_admin:
    entities:
        WebTexto:
            disabled_actions: ['delete']
            class: App\Entity\WebTexto
            form:
                fields:
                  - { type: 'group', columns: 12, label: 'Banner' }
                  - { property: 'tituloHeader' }
                  - { property: 'subTituloHeader' }
                  - { type: 'group', columns: 12, label: 'Inicio' }
                  - { property: 'mostrarTips' }
                  - { property: 'acercaDe', type: 'fos_ckeditor' }
                  - { property: 'tituloConsejos' }
                  - { property: 'concejos', type: 'fos_ckeditor' }
                  - { type: 'group', columns: 12, label: 'Comercios' }
                  - { property: 'linkFormularioInscripcionComercios' }
                  - { property: 'textoParaComercios', type: 'fos_ckeditor', type_options: { config: { filebrowserUploadRoute: 'upload_file_entry'} } }
                  - { type: 'group', columns: 6, label: 'Contacto' }
                  - { property: 'contactoDireccion' }
                  - { property: 'contactoTelefono' }
                  - { property: 'contactoWhatsapp' }
                  - { type: 'group', columns: 6, label: 'Social' }
                  - { property: 'instagram' }
                  - { property: 'facebook' }
                  - { property: 'twitter' }
                  - { property: 'youtube' }